### ISSUE TITLE
Duotone

### ISSUE THREAD

**Issue by Arlovas** [omacranger/fontawesome-subset#2]
How can I add doutone on webfonts generation ?

**Comment by Arlovas** [comment]
I added doutone on font_maps and get this error: Checksum error in glyf, woff and woff2 are not generated

**Comment by omacranger** [comment]
Hey @Arlovas, currently Duotone icons are not supported. The glyphs are generated a bit differently than the other fonts since they're two separate layers so I'll have to rework a portion of this to bring that feature in. Thanks for bringing it up!

**Comment by Arlovas** [comment]
Thanks for the reply. For now I'm adding all fonts for duotone when necessary, I'll be watching for news. btw great work @omacranger !

**Comment by omacranger** [comment]
@Arlovas Hey there! I've added some initial support for duotone fonts on the `development` branch. If you're able to grab a copy from there and give it a shot you should be able to generate optimized versions of those fonts as of the latest commit. You will need to make sure you have the Pro version of FontAwesome installed and including one of the versions that supports Duotone. 

You should be able to install that specific branch for testing by using the following command: `npm install omacranger/fontawesome-subset#development --save`. Give it a shot and let me know if it's working as you'd expect!

**Comment by boyanraichev** [comment]
Just used this today - great package and duotone seems to work as well! Thanks

**Comment by omacranger** [comment]
Thanks for the feedback @boyanraichev.

This has been added / released as of version 1.1.0, available on Github and NPM.

**Comment by Arlovas** [comment]
@omacranger Thx, for implementing this. Good job :)
