### ISSUE TITLE
Custom icon

### ISSUE THREAD

**Issue by Cedric-ruiu** [omacranger/fontawesome-subset#27]
Hello,

I use the pro version with FontAwesome Kits, but I want to switch to self hosting fonts to improve performance. Subsetter software is easy to use but don't provide feature to add custom icon.

Any plan to add feature for support custom icons with fontawesome-subset ?

Cédric

**Comment by omacranger** [comment]
Hey Cédric. I think that's a bit outside of the scope of this project unfortunately.
