### ISSUE TITLE
Make font-awesome free dependency optional

### ISSUE THREAD

**Issue by Steeff0** [omacranger/fontawesome-subset#5]
Hello,

I found this project to make a font-awesome subset (nice project btw) and want to use it to amek a font-awesome pro subset. When I install this project as dependency it automatically downloads font-awesome free as well, while I don't need it.

Could font-awesome free moved from the dependencies to the optional dependencies?

Regards.

**Comment by omacranger** [comment]
@Steeff0 thanks for the suggestion. I'd definitely like to rework how the dependencies are being loaded so I'll keep this open until it's resolved.

**Comment by omacranger** [comment]
@Steeff0 This should be resolved with release `2.0.0`.
